# Generated by Django 4.2.5 on 2023-12-03 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='community_space',
            new_name='community_spacea',
        ),
    ]
