# Generated by Django 4.2.5 on 2023-10-17 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customuser_calle_customuser_comuna_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySpace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_capacity', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JuntaDeVecinos',
            fields=[
                ('hoa_id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12)),
                ('legal_address', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('foundation_date', models.DateField(blank=True, null=True)),
                ('logo_symbol', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin_general',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_hoa_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('resident_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('hoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.juntadevecinos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResidenceCertificate',
            fields=[
                ('certificate_id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_date', models.DateField()),
                ('certificate_filename', models.CharField(max_length=255)),
                ('certificate_status', models.CharField(max_length=50)),
                ('generated_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residence_certificates_generated', to=settings.AUTH_USER_MODEL)),
                ('hoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.juntadevecinos')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residence_certificates_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('reservation_status', models.CharField(max_length=20)),
                ('community_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.communityspace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('publication_date', models.DateField()),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_content', models.TextField()),
                ('send_date_time', models.DateTimeField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
