# Generated by Django 4.2.5 on 2023-10-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_communityspace_juntadevecinos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juntadevecinos',
            name='hoa_name',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
