# Generated by Django 4.2.5 on 2023-11-13 16:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencecertificate',
            name='verification_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
