# Generated by Django 4.2.5 on 2023-11-12 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_solnoticias_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solnoticias',
            name='titulo',
        ),
    ]
