# Generated by Django 4.2.5 on 2023-11-13 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_residencecertificate_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='residence_certificates_received',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residence_certificates_received', to='main.residencecertificate'),
        ),
    ]
