# Generated by Django 4.2.5 on 2023-11-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_solnoticias_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='solnoticias',
            name='estado',
            field=models.CharField(choices=[('nueva', 'Nueva'), ('eliminada', 'Eliminada')], default='nueva', max_length=20),
        ),
    ]
