# Generated by Django 4.2.5 on 2023-11-13 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_resident_residence_certificates_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='residence_certificates_received',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residence_certificates_received', to='main.residencecertificate'),
        ),
    ]
