# Generated by Django 4.2.5 on 2023-11-12 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_noticia_solnoticias_estado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='solnoticias',
            new_name='crearsol',
        ),
    ]
