# Generated by Django 4.2.5 on 2023-11-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_resident_residence_certificates_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='residence_certificates_received',
        ),
    ]
