# Generated by Django 4.2.5 on 2023-11-13 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_solnoticias_crearsol'),
    ]

    operations = [
        migrations.AddField(
            model_name='crearsol',
            name='usersol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
