# Generated by Django 4.2.5 on 2023-11-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_crearsol_usersol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
