# Generated by Django 4.2.5 on 2023-11-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_resident_residence_certificates_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='juntadevecinos',
            name='legal_representative_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juntadevecinos',
            name='legal_representative_rut',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juntadevecinos',
            name='legal_representative_rut1',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residencecertificate',
            name='certificate_filename2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
