# Generated by Django 4.2.5 on 2023-11-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_juntadevecinos_legal_representative_rut1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juntadevecinos',
            name='legal_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='juntadevecinos',
            name='legal_representative_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='juntadevecinos',
            name='legal_representative_rut',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='juntadevecinos',
            name='rut',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
