# Generated by Django 4.2.5 on 2023-11-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_juntadevecinos_legal_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juntadevecinos',
            name='image',
            field=models.ImageField(default=1, upload_to='uploads/product/'),
            preserve_default=False,
        ),
    ]
