# Generated by Django 4.2.5 on 2023-11-16 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_juntadevecinos_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juntadevecinos',
            old_name='signatue_img',
            new_name='signature_img',
        ),
    ]
