# Generated by Django 4.2.5 on 2023-11-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_signatue_img_juntadevecinos_signature_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juntadevecinos',
            name='logo_symbol',
            field=models.ImageField(blank=True, upload_to='uploads/logos/'),
        ),
        migrations.AlterField(
            model_name='juntadevecinos',
            name='signature_img',
            field=models.ImageField(blank=True, upload_to='uploads/signatures/'),
        ),
    ]
