# Generated by Django 4.2.5 on 2023-11-16 04:01

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_signatue_img_juntadevecinos_signature_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juntadevecinos',
            name='logo_symbol',
            field=models.ImageField(blank=True, upload_to='uploads/logos/'),
        ),
        migrations.AlterField(
            model_name='juntadevecinos',
            name='signature_img',
            field=models.ImageField(blank=True, upload_to='uploads/signatures/'),
        ),
        
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crearsol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('eliminada', 'Eliminada')], default='nueva', max_length=20)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.TextField()),
                ('usersol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='resident',
            name='hoa',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='main.juntadevecinos'),
        ),
    ]
