# Generated by Django 4.2.5 on 2023-11-18 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_crearsol_usersol'),
        ('main', '0021_alter_juntadevecinos_logo_symbol_and_more'),
    ]

    operations = [
    ]
