# Generated by Django 4.2.5 on 2023-11-24 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_noticia_crearsol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='hoa',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='main.juntadevecinos'),
        ),
    ]
