# Generated by Django 4.2.5 on 2023-11-25 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
