# Generated by Django 4.2.5 on 2023-11-25 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_region_capital_regional2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='username',
        ),
        migrations.AlterField(
            model_name='resident',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
