# Generated by Django 4.2.5 on 2023-11-25 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_resident_username_alter_resident_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='username',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='resident',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
