# Generated by Django 4.2.5 on 2023-11-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_userauditlog_reservationauditlog_newsauditlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
