# Generated by Django 4.2.5 on 2023-12-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_customuser_numero_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='utilityBill',
            field=models.FileField(blank=True, null=True, upload_to='utilityBills/'),
        ),
    ]
