# Generated by Django 4.2.5 on 2023-12-03 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_customuser_utilitybill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
